### ISSUE TITLE
BdSeq Number and Message Seq Number. Are those seq numbers in an order?

### ISSUE THREAD

**Issue by nalamatitejasree** [Cirrus-Link/Sparkplug#17]
Hello, I am using C# Sparkplug library and trying to publish data. I need a clarification about BdSeq number and message Seq number.

Should we use only one variable for seq number? Start at 0 and increment till 255 when publishing NBIRTH, DBIRTH, NDATA and DDATA? what is the difference between BdSeq number and message Seq number.

Also, I have seen the metric for Bdseqnum takes a datatype of UInt64. If the limit is only till 255, why are we using UInt64?

Thanks.

**Comment by jbrzozoski** [comment]
To the best of my understanding, message sequence number resets to 0 each time you need to publish NBIRTH and goes up by one for all other messages.  The bdSeq (which is optional) is supposed to go up by one each time a client connects to a broker, meaning if you publish multiple NBIRTH messages during the same session that they will all have the same bdSeq.  Ideally, a client would retain its bdSeq number eternally and increment by one each new TCP session.  The goal of the bdSeq is to allow easier tracking of lost connections, and matching NDEATH messages to NBIRTH, but a client can only setup the NDEATH once at the beginning of a session in the WILL of the CONNECT.

**Comment by ckienle** [comment]
@jbrzozoski is correct
The "seq" number is used for sequencing all messages published by a Sparkplug client application and resets to 0 upon a new NBIRTH message. 

The "bdSeq" number is used to match NDEATH messages with their corresponding NBIRTH message. They are only incremented when a new session is established and a new NBIRTH is published. One reason for this is because it is possible (in some client/server implementations) for an NDEATH (published as an LWT by the MQTT server) of a disconnected client to be delivered after the client has already reconnected and published a new NBIRTH.  The receiving application should compare the "bdSeq" number of the NDEATH with the "bdSeq" number of the last NBIRTH that was received to see if it represents the "death" of the current session, or if it was for a past session.

Also, the project has been moved. Please post future questions and discussion here [https://github.com/eclipse/tahu](url)
